CREATE TABLE projects(
    id INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
    name VARCHAR(100),
    created_at DATETIME NOT NULL
);

CREATE TABLE sprints(
    id INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
    project_id INT UNSIGNED NOT NULL,
    name VARCHAR(100),
    hours SMALLINT UNSIGNED NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    created_at DATETIME NOT NULL
);

CREATE TABLE burndown(
    id INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
    sprint_id INT UNSIGNED NOT NULL,
    remaining_hours SMALLINT UNSIGNED NOT NULL,
    day DATE NOT NULL
);
